package com.online.taxi.mapper;

import com.online.taxi.entity.CarLevel;
import org.springframework.stereotype.Service;

/**
 * 车辆级别mapper
 *
 * @author dongjb
 * @date 2021/04/16
 */
@Service
public interface CarLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_car_level
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_car_level
     *
     * @mbggenerated
     */
    int insert(CarLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_car_level
     *
     * @mbggenerated
     */
    int insertSelective(CarLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_car_level
     *
     * @mbggenerated
     */
    CarLevel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_car_level
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CarLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_car_level
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CarLevel record);
}
