package com.online.taxi.mapper;

import com.online.taxi.entity.ChargeRule;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;

/**
 * 费用规则mapper
 *
 * @author dongjb
 * @date 2021/04/16
 */
@Service
public interface ChargeRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_charge_rule
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_charge_rule
     *
     * @mbggenerated
     */
    int insert(ChargeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_charge_rule
     *
     * @mbggenerated
     */
    int insertSelective(ChargeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_charge_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChargeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_charge_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChargeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_charge_rule
     *
     * @mbggenerated
     */
    List<ChargeRule> selectByPrimaryKey(ChargeRule chargeRule);
}
